package br.com.prognum.gateway_certidao.docket_core.models;

public enum DocumentoStatus {
	NOVO, EM_ANDAMENTO, ENTREGUE, FINALIZADO_PELO_CLIENTE, PENDENTE, CANCELADO, PROCESSANDO_CANCELAMENTO, EXCLUIDO,
	PENDENTE_APROVACAO_REABERTURA, AGUARDANDO_APROVACAO, REPROVADO, AGUARDANDO_PAGAMENTO, PAGAMENTO_RECUSADO,
	PAGAMENTO_ESTORNADO, PAGAMENTO_EM_ANALISE
}
